version: '3.8'
name: 'desafio-sharenergy'
services:

  db:
    container_name: sharenergy-db
    image: mongo:latest
    env_file:
       - .env
    ports:
     - ${DB_PORT}:${DB_PORT}
    volumes:
      - mongodb_data_container:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:${DB_PORT} --quiet
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: 'always'

  api:
    container_name: sharenergy-api
    build: ./api
    working_dir: /api
    volumes:
      - ./api/src:/api/src
    ports:
      - ${API_PORT}:${API_PORT}
    command: npm run start:dev
    env_file:
       - .env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:${API_PORT}"]
      timeout: 10s
      retries: 5
  
  web:
    container_name: web
    build: ./web
    working_dir: /web
    volumes:
      - ./web/src:/web/src
    env_file:
      - .env
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:${WEB_PORT}"]
      timeout: 10s
      retries: 5

volumes:
  mongodb_data_container:
